# WARNING: This environment file hasn't been tested
name: rinalmo
channels:
  - pytorch
  - nvidia
  - bioconda
  - conda-forge
dependencies:
  - biopython
  - blas
  - blas-devel
  - bleach
  - brotli-python
  - bzip2
  - ca-certificates
  - cd-hit
  - certifi
  - charset-normalizer
  - click
  - colorama
  - cuda-cudart
  - cuda-cupti
  - cuda-libraries
  - cuda-nvrtc
  - cuda-nvtx
  - cuda-runtime
  - docker-pycreds
  - filelock
  - fsspec
  - gitdb
  - gitpython
  - gmp
  - gmpy2
  - icu
  - idna
  - jinja2
  - kaggle
  - ld_impl_linux-64
  - lightning
  - lightning-utilities
  - llvm-openmp
  - markupsafe
  - mpc
  - mpfr
  - mpmath
  - numpy
  - openssl
  - pip
  - python
  - pytorch
  - pytorch-cuda
  - pytorch-lightning
  - pytorch-mutex
  - pyyaml
  - readline
  - requests
  - sentry-sdk
  - seqkit
  - setproctitle
  - setuptools
  - six
  - smmap
  - sympy
  - tbb
  - text-unidecode
  - tk
  - torchmetrics
  - torchtriton
  - tqdm
  - typing-extensions
  - typing_extensions
  - urllib3
  - wandb
  - webencodings
  - wheel
  - xz
  - yaml
  - zlib
  - scipy
  - einops
  - pip:
      - flash-attn==2.3.2
      - ml-collections
      - gdown
